'use client';

import { Recipe } from '@/lib/types';
import { Share2, Copy, Download, Check } from 'lucide-react';
import { useState } from 'react';

interface RecipeShareProps {
  recipe: Recipe;
}

export default function RecipeShare({ recipe }: RecipeShareProps) {
  const [copied, setCopied] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  const recipeUrl = `${typeof window !== 'undefined' ? window.location.origin : ''}/recipe/${recipe.id}`;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(recipeUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateMarkdown = () => {
    const ingredients = recipe.ingredients
      .map((ing: any) => `- ${ing.amount} ${ing.unit} ${ing.item}${ing.notes ? ` (${ing.notes})` : ''}`)
      .join('\n');

    const instructions = recipe.instructions
      .map((inst: any) => `${inst.step}. ${inst.instruction}${inst.tip ? ` - *${inst.tip}*` : ''}`)
      .join('\n');

    return `# ${recipe.title}

${recipe.description || ''}

## Details
- **Servings:** ${recipe.servings}
- **Prep Time:** ${recipe.prep_time_minutes || 0} minutes
- **Cook Time:** ${recipe.cook_time_minutes || 0} minutes
- **Difficulty:** ${recipe.difficulty || 'N/A'}
- **Cuisine:** ${recipe.cuisine_type || 'N/A'}

## Ingredients
${ingredients}

## Instructions
${instructions}

${recipe.chef_notes ? `## Chef's Notes\n${recipe.chef_notes}` : ''}

---
*Generated by FoodML Recipe Lab*
*${recipeUrl}*`;
  };

  const handleDownloadMarkdown = () => {
    const markdown = generateMarkdown();
    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/markdown;charset=utf-8,' + encodeURIComponent(markdown));
    element.setAttribute('download', `${recipe.title.replace(/\s+/g, '_').toLowerCase()}.md`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: recipe.title,
          text: recipe.description || 'Check out this recipe!',
          url: recipeUrl,
        });
      } catch (err) {
        console.log('Share cancelled');
      }
    }
  };

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        className="btn btn-secondary flex items-center space-x-2"
      >
        <Share2 className="w-5 h-5" />
        <span>Share</span>
      </button>

      {showMenu && (
        <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg z-10 border border-gray-200">
          <button
            onClick={handleCopyLink}
            className="w-full px-4 py-2 text-left hover:bg-gray-50 flex items-center space-x-2 border-b border-gray-200"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-green-600" />
                <span className="text-green-600">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>Copy Link</span>
              </>
            )}
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="w-full px-4 py-2 text-left hover:bg-gray-50 flex items-center space-x-2 border-b border-gray-200"
          >
            <Download className="w-4 h-4" />
            <span>Download as Markdown</span>
          </button>

          {navigator.share && (
            <button
              onClick={handleShare}
              className="w-full px-4 py-2 text-left hover:bg-gray-50 flex items-center space-x-2"
            >
              <Share2 className="w-4 h-4" />
              <span>Share...</span>
            </button>
          )}
        </div>
      )}
    </div>
  );
}
